clc; clear; close all;

% Plot median convergence curves from the MAT file generated by:
%   run_cec2017_50D_all.m

result_mat = fullfile('results_cec2017', ...
    'results_CEC2017_8alg_D50_N50_FEs100000_Runs30.mat');

show_iqr = false;
export_png = true;
export_pdf = true;

assert(isfile(result_mat), ...
    'Cannot find result MAT file: %s', result_mat);

load(result_mat, 'config', 'curve_error_sampled');

alg_names = config.alg_names;
func_list = config.func_list;
fes_show = config.fes_show;

nFunc = numel(func_list);
nAlg = numel(alg_names);

line_styles = {'-o','-^','-x','-*','-d','-s','-p','-v'};
colors = lines(nAlg);

marker_idx = unique([1:250:numel(fes_show), numel(fes_show)]);

figure('Color','w','Position',[120 60 1100 940]);

tl = tiledlayout(3, 2, ...
    'Padding','loose', ...
    'TileSpacing','loose');

for p = 1:nFunc
    ax = nexttile(tl, p);

    hold(ax, 'on');
    box(ax, 'on');
    grid(ax, 'on');

    for alg_id = 1:nAlg
        run_curves = double(squeeze(curve_error_sampled(:, p, alg_id, :)));
        run_curves = reshape(run_curves, config.Runs, []);

        med_curve = median(run_curves, 1);

        if show_iqr
            q1 = percentile_over_runs(run_curves, 0.25);
            q3 = percentile_over_runs(run_curves, 0.75);

            fill(ax, ...
                [fes_show, fliplr(fes_show)], ...
                [q1, fliplr(q3)], ...
                colors(alg_id, :), ...
                'FaceAlpha',0.08, ...
                'EdgeColor','none', ...
                'HandleVisibility','off');
        end

        semilogy(ax, fes_show, med_curve, line_styles{alg_id}, ...
            'LineWidth',1.25, ...
            'MarkerIndices',marker_idx, ...
            'MarkerSize',5, ...
            'Color',colors(alg_id,:), ...
            'DisplayName',alg_names{alg_id});
    end

    title(ax, sprintf('F%d', func_list(p)));
    xlim(ax, [1, config.MaxFEs]);

    xlabel(ax, 'Function Evaluations (FEs)');
    ylabel(ax, 'Objective error |f(x)-f^*|');

    if p == 2
        legend(ax, 'Location','northeast');
    end
end

sgtitle(tl, sprintf( ...
    'CEC2017 median convergence curves over %d runs (D = %d)', ...
    config.Runs, config.D));

if export_png
    exportgraphics(gcf, ...
        sprintf('CEC2017_convergence_8alg_D%d_median.png', config.D), ...
        'Resolution',600);
end

if export_pdf
    exportgraphics(gcf, ...
        sprintf('CEC2017_convergence_8alg_D%d_median.pdf', config.D), ...
        'ContentType','vector');
end

function qv = percentile_over_runs(A, q)
A = sort(A, 1);
n = size(A, 1);

if n == 1
    qv = A;
    return;
end

pos = 1 + (n - 1) * q;
lo = floor(pos);
hi = ceil(pos);
w = pos - lo;

if lo == hi
    qv = A(lo, :);
else
    qv = (1 - w) .* A(lo, :) + w .* A(hi, :);
end
end
